### ISSUE TITLE
使用一段时间后重启报错

### ISSUE THREAD

**Issue by artxia** [SharzyL/tg_searcher#10]
**Bug 描述**

安装部署后可以正常使用，但是在使用一天后因 断电被关闭。
再次重启失败，出现下面日志的提示。
多次尝试重启，都不能成功。

尝试删除 `tg_searcher_data/xiasearcher/index/priv_idx` 文件夹后，可以正常启动。但是原有的索引记录全部丢失。

**日志**
```
INFO:telethon.network.mtprotosender:Connecting to 91.108.56.101:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 91.108.56.101:443/TcpFull complete!
INFO:session:xia:Start iterating dialogs
INFO:session:xia:End iterating dialogs, 439 dialogs in total
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 53, in a_main
    backend = BackendBot(common_config, backend_config, sessions[session_name], args.clear, backend_id)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/backend_bot.py", line 29, in __init__
    self._indexer: Indexer = Indexer(common_cfg.index_dir / backend_id, clean_db)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/indexer.py", line 80, in __init__
    if index.exists_in(index_dir, index_name) \
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 136, in exists_in
    ix = open_dir(dirname, indexname=indexname)
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/usr/local/lib/python3.9/site-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/usr/local/lib/python3.9/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint
    return read_varint(self.read)
  File "/usr/local/lib/python3.9/site-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found

```

**Comment by SharzyL** [comment]
底层的 whoosh 库并不保证 crash safety，所以这可能是因为断电导致的数据损坏。这只能通过更换底层的索引库，或者上游 whoosh 支持 crash safety 来解决。用户可以通过 `/download_chat` 重新建立索引。
