### ISSUE TITLE
配置示例说可以不配置proxy，但是去掉该配置报错

### ISSUE THREAD

**Issue by zengge99** [SharzyL/tg_searcher#11]
root@vm:~/tg_searcher# python3 -m tg_searcher
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/tg_searcher/main.py", line 79, in main
    asyncio.run(a_main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/tg_searcher/main.py", line 29, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'

**Comment by zengge99** [comment]
不能删掉proxy:行，只是删除冒号后面内容即可。
