### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'config/searcher.yaml'

### ISSUE THREAD

**Issue by stainge** [SharzyL/tg_searcher#13]
**Bug 描述**
参考docker-compose部署，运行到`docker start -ia tg_searcher`时报错，程序无法启动

**复现方式**
复现 bug 的步骤：
参考docker-compose部署，运行到`docker start -ia tg_searcher`时报错。
文件目录架构：
```
└─ tg_searcher
   ├─ config
   |  └─ searcher.yaml
   └─ docker-compose.yaml
```

**日志**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 29, in a_main
    full_config = yaml.safe_load(Path(args.config).read_text())
  File "/usr/local/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'config/searcher.yaml'
```

**Comment by SharzyL** [comment]
这是由于使用 pip 安装 tg_searcher 之后程序运行路径发生变化导致的 bug，解决方法是将 docker-compose.yaml 中的配置文件路径从 `./config/searcher.yaml` 更改为 `/app/config/searcher.yaml`，见 42f434c。近日会将其合并至 master 分支。
