### ISSUE TITLE
docker-compose版 在初次运行时报python3.9错误

### ISSUE THREAD

**Issue by ziisp** [SharzyL/tg_searcher#19]
**Bug 描述**
在初次执行 docker start -ia tg_searcher时出现如下报错
`[root@netcup tg_searcher]# docker start -ia tg_searcher

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
`

**复现方式**
复现 bug 的步骤：
1. 使用 tg_searcher 的latest版本（两个月前更新的版本）
2. 使用了配置文件
```yaml
common:
  name: tg_search
  runtime_dir: /app/config/tg_searcher_data
  api_id: 10******5
  api_hash: 562e0e*********7b012
...
frontends:
  - type: bot
    id: public
    use_backend: pub_idx
    config:
      admin_id: 28*****2
      bot_token: 55*********************IU4
      redis: localhost:6379
...
backends:
  - id: pub_index
    use_session: alice
    config:
      monitor_all: true
      excluded_chats:
        - 342843148
        - 857204339
...
```
3. 使用管理员帐号发送 …… 命令
4. 发生异常：……

**期望行为**
你期望发生的行为

**日志**
```
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
    asyncio.run(a_main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 30, in a_main
    common_config = CommonBotConfig(**full_config['common'])
TypeError: __init__() missing 1 required positional argument: 'proxy'
...
```

**Comment by SharzyL** [comment]
感谢反馈！

这个 bug 是由于对于 proxy 配置缺失的情形处理不当导致的，在目前的 dev 分支里面应当已修复，不过这一修复还没有生成 docker 镜像，建议使用源代码进行手动部署。

**Comment by ziisp** [comment]
> 感谢反馈！
> 
> 这个错误源代码是由于配置的情况而导致的，在当前的开发代理分支中还出现了一些处理情况，但是这个修复没有生成 docker 建议，建议使用进行手动部署。

计划什么时候迭代docker版本啊，感觉docker版的还是比较方便一些

**Comment by SharzyL** [comment]
latest 已经迭代到了修复后的版本
