### ISSUE TITLE
Message was too long

### ISSUE THREAD

**Issue by artxia** [SharzyL/tg_searcher#24]
不知道是不是因为我加入的群太多。。最近出现这种情况

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/frontend_bot.py", line 325, in bot_message_handler
    await self._admin_msg_handler(event)
  File "/usr/local/lib/python3.9/site-packages/tg_searcher/frontend_bot.py", line 176, in _admin_msg_handler
    await event.respond(await self.backend.get_index_status(), parse_mode='html')
  File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/message.py", line 756, in respond
    return await self._client.send_message(
  File "/usr/local/lib/python3.9/site-packages/telethon/client/messages.py", line 885, in send_message
    result = await self(request)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.MessageTooLongError: Message was too long (caused by SendMessageRequest)`

**Comment by SharzyL** [comment]
Try this simple fix (99344da9953eaa4162f104373f1d80f31937ec57)

**Comment by artxia** [comment]
```
ERROR:telethon.client.updates:Unhandled exception on bot_message_handler

Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 483, in _dispatch_update
await callback(event)
File "/usr/local/lib/python3.9/site-packages/tg_searcher/frontend_bot.py", line 367, in bot_message_handler
raise e
File "/usr/local/lib/python3.9/site-packages/tg_searcher/frontend_bot.py", line 362, in bot_message_handler
await self._admin_msg_handler(event)
File "/usr/local/lib/python3.9/site-packages/tg_searcher/frontend_bot.py", line 200, in _admin_msg_handler
await event.respond(await self.backend.get_index_status(), parse_mode='html')
File "/usr/local/lib/python3.9/site-packages/telethon/tl/custom/message.py", line 756, in respond
return await self._client.send_message(
File "/usr/local/lib/python3.9/site-packages/telethon/client/messages.py", line 885, in send_message
result = await self(request)
File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 30, in __call__
return await self._call(self._sender, request, ordered=ordered)
File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 84, in _call
result = await future
telethon.errors.rpcerrorlist.MessageTooLongError: Message was too long (caused by SendMessageRequest)
```

更新最新提交https://github.com/SharzyL/tg_searcher/commit/99344da9953eaa4162f104373f1d80f31937ec57 后，
默认启动报错消失
`/stat` 操作还是会有这个报错。

**Comment by SharzyL** [comment]
Try [fix-stat-msg-length](https://github.com/SharzyL/tg_searcher/tree/fix-stat-msg-length) branch. I do not have a session with so many chats to monitor, hence it is hard for me to test it out.

**Comment by artxia** [comment]
> Try [fix-stat-msg-length](https://github.com/SharzyL/tg_searcher/tree/fix-stat-msg-length) branch. I do not have a session with so many chats to monitor, hence it is hard for me to test it out.

经过测试该分支，可以正常运行，不再报长度错误。
同时消息过长后的提示“由于 Telegram 消息长度限制，部分对话的统计信息没有展示”，也正常展示。

建议合并到主要分支
