### ISSUE TITLE
Connection to Telegram failed 5 time(s)

### ISSUE THREAD

**Issue by artxia** [SharzyL/tg_searcher#27]
我是使用docker方式运行的bot
出现这个提示的原因是代理突然断网，导致bot无法连接服务器。
多次尝试重连后，bot自动关闭docker运行。

期待的方式：bot继续尝试通信，直到网络恢复

日志文件
```
WARNING:telethon.network.mtprotosender:Attempt 6 at connecting failed: ConnectionError: [Errno 111] Could not connect to proxy 192.168.1.4:1081 [Connect call failed ('192.168.1.4', 1081)]

INFO:telethon.network.mtprotosender:Failed reconnection attempt 5 with ConnectionError

INFO:telethon.network.mtprotosender:Failed reconnection attempt 5 with ConnectionError

ERROR:telethon.network.mtprotosender:Automatic reconnection failed 5 time(s)

INFO:telethon.network.mtprotosender:Disconnecting from 91.108.56.101:443/TcpFull...
ERROR:telethon.network.mtprotosender:Automatic reconnection failed 5 time(s)

INFO:telethon.network.mtprotosender:Disconnecting from 91.108.56.101:443/TcpFull...
INFO:telethon.network.mtprotosender:Disconnection from 91.108.56.101:443/TcpFull complete!
INFO:telethon.network.mtprotosender:Disconnection from 91.108.56.101:443/TcpFull complete!
INFO:telethon.network.mtprotosender:Not disconnecting (already have no connection)
Traceback (most recent call last):
File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.9/site-packages/tg_searcher/__main__.py", line 3, in <module>
main()
File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 82, in main
asyncio.run(a_main())
File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/usr/local/lib/python3.9/site-packages/tg_searcher/main.py", line 78, in a_main
await frontend.bot.run_until_disconnected()
File "/usr/local/lib/python3.9/site-packages/telethon/client/updates.py", line 33, in _run_until_disconnected
result = await self.disconnected
ConnectionError: Connection to Telegram failed 5 time(s)

start search
start search
```

**Comment by SharzyL** [comment]
断连重试的逻辑在代码中实现起来较为复杂，可以使用 docker 自带的[重启策略](https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy)作为替代
